### ISSUE TITLE
"Don't be a dick"

### ISSUE THREAD

**Issue by madebysheppard** [coopdigital/feedback-posters#1]
I feel that "Don't be a dick" isn't a great term, it:

- is a term favoured by tech bros the world over
- assumes people know when they're being "a dick" 
- is vague enough that people can (and will) absolve themselves of all dickishness
- implies that by default Co-op and the team _aren't_ dicks (which although very true, you're all lovely people, is maybe too pro-corporate?)
- can give people free reign to label people who disagree with them as 'dicks'

Maybe it's more helpful to ask people to be respectful or something like that.

(This is all personal opinion after working with an organisation that loves to tout not being a dick)

**Comment by digin8** [comment]
Fixed this in the next release. Thanks Jack.
